import Head from 'next/head';
import { BsFillMoonStarsFill } from 'react-icons/bs';
import { AiFillLinkedin, AiFillGithub } from 'react-icons/ai';
import Image from 'next/image';
import devEdWave from '../public/dev-ed-wave.png';
import mobile from '../public/smartphone.png';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Mina Tawfik Portfolio</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='bg-white px-10'>
        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-burtons'>DevelopedBy</h1>
            <ul className='flex items-center'>
              <li>
                <BsFillMoonStarsFill className='text-2xl ' />
              </li>
              <li>
                <a
                  className='bg-gradient-to-r from-cyan-500 to-teal-500 px-4 py-2 ml-8 rounded-md'
                  href='#'
                >
                  {' '}
                  Resume{' '}
                </a>
              </li>
            </ul>
          </nav>
          <div className='text-center p-8'>
            <h2 className='text-5xl py-2 text-teal-600 font-bold'>
              Mina Tawfik
            </h2>
            <h3 className='text-2xl py-2'>Lead/Senior Full-Stack</h3>
            <p className='text-md py-5 leading-8 text-gray-800'>
              {' '}
              Freelancer Full-Stack providing services for website programming
              and mobile. Join me down below and let's get cracking!
            </p>
            <div className='flex text-4xl justify-center gap-16 text-gray-600'>
              <AiFillLinkedin />
              <AiFillGithub />
            </div>
          </div>
          <div className='relative mx-auto mt-20 bg-gradient-to-b from-teal-500 h-80 w-80 rounded-full overflow-hidden'>
            <Image src={devEdWave} fill objectFit='fit' alt='icon' />
          </div>
        </section>
        <section>
          <div>
            <h3 className='text-3xl py-5'>Services I offer</h3>
            <p className='text-md py-2 leading-8 text-gray-800'>
              {' '}
              Since the beginning of my journey as a freelance developer, I've
              done remote work for{' '}
              <span className='text-teal-500'> agencies </span>
              consulted for <span className='text-teal-500'>startups </span>
              and collaborated with talanted people to create Mobiel apps and
              websites for both companies and individual users.
            </p>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-gray-200'>
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p>
          </div>
          <div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1'>
              <Image
                className='mx-auto'
                src={mobile}
                width={100}
                height={100}
                alt='mobile'
              />
              <h3 className='text-lg font-medium pt-8 pb-2  '>
                Mobile Service
              </h3>
              <p className='py-2'>
                Creating elegant mobile apps suited for your needs.
              </p>
              <h4 className='py-4 text-teal-600'>Platform I Use</h4>
              <p className='text-gray-800 py-1'>Native Android</p>
              <p className='text-gray-800 py-1'>Native iOS</p>
              <p className='text-gray-800 py-1'>Xamarin</p>
              <p className='text-gray-800 py-1'>React Native</p>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
