import Head from 'next/head';
import { useState } from 'react';

import Image from 'next/image';
import devEdWave from '../public/dev-ed-wave.png';
import mobile from '../public/smartphone.png';
import code from '../public/code.png';
import Navbar from '../components/Navbar';
import SocialIcons from '../components/SocialIcons';

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? 'dark' : ''}>
      <Head>
        <title>Mina Tawfik Portfolio</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40'>
        <section className='min-h-screen'>
          <Navbar darkMode={darkMode} setDarkMode={setDarkMode} />
          <div className='text-center p-8'>
            <h2 className='text-5xl py-2 text-teal-600 font-bold dark:text-teal-400 md:text-6xl'>
              Mina Tawfik
            </h2>
            <h3 className='text-2xl py-2 dark:text-white md:text-3xl'>
              Lead/Senior Full-Stack
            </h3>
            <p className='text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl'>
              {' '}
              Freelancer Full-Stack providing services for website programming
              and mobile. Join me down below and let's get cracking!
            </p>
            <SocialIcons />
          </div>
          <div className='relative mx-auto mt-20 bg-gradient-to-b from-teal-500 h-80 w-80 rounded-full overflow-hidden md:h-96 md:w-96'>
            <Image src={devEdWave} fill objectFit='fit' alt='icon' />
          </div>
        </section>
        <section>
          <div>
            <h3 className='text-3xl py-5 dark:text-white'>Services I offer</h3>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-gray-200'>
              {' '}
              Since the beginning of my journey as a freelance developer, I've
              done remote work for{' '}
              <span className='text-teal-500'> agencies </span>
              consulted for <span className='text-teal-500'>startups </span>
              and collaborated with talanted people to create Mobiel apps and
              websites for both companies and individual users.
            </p>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-gray-200'>
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p>
          </div>
          <div className='lg:flex gap-10'>
            <div className='text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1'>
              <Image
                className='mx-auto'
                src={mobile}
                width={100}
                height={100}
                alt='mobile'
              />
              <h3 className='text-lg font-medium pt-8 pb-2  '>
                Mobile Service
              </h3>
              <p className='py-2'>
                Creating elegant mobile apps suited for your needs.
              </p>
              <h4 className='py-4 text-teal-600'>Platform I Use</h4>
              <p className='text-gray-800 py-1'>Native Android</p>
              <p className='text-gray-800 py-1'>Native iOS</p>
              <p className='text-gray-800 py-1'>Xamarin</p>
              <p className='text-gray-800 py-1'>React Native</p>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1'>
              <Image
                className='mx-auto'
                src={code}
                width={100}
                height={100}
                alt='mobile'
              />
              <h3 className='text-lg font-medium pt-8 pb-2  '>
                Code your dream website
              </h3>
              <p className='py-2'>
                Do you have an idea for your next great website? Let's make it a
                reality.{' '}
              </p>
              <h4 className='py-4 text-teal-600'>Platform I Use</h4>
              <p className='text-gray-800 py-1'>React.JS</p>
              <p className='text-gray-800 py-1'>Next.JS</p>
              <p className='text-gray-800 py-1'>TypeScript</p>
              <p className='text-gray-800 py-1'>JavaScript</p>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
